php5:
    image: apache:php5
    volumes:
        - ./data/:/var/www/html/
    ports:
        - "80"
ha:
    image: tutum/haproxy
    links: 
        - php5
    ports:
        - "80:80"
    environment:
        - BACKEND_PORT=80
        - BALANCE=roundrobin